# Generated by Django 3.2.18 on 2023-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=100)),
                ('producto_descripcion', models.TextField(blank=True, null=True)),
                ('producto_imagen', models.CharField(blank=True, max_length=120, null=True)),
                ('producto_precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('producto_estado', models.BooleanField(default=True)),
                ('producto_stock', models.IntegerField()),
            ],
        ),
    ]
